### PR TITLE
-stub flag

### LINKED ISSUE #36: Function that do not return values should not be mandatory
I'm interested in making mocks more lenient (in the style of Mockito). That is, when a function does not return any value, then it should probably not be mandatory.
In other words, the mock should not panic when called on a function that is nil, as long as it does not return any value.

Thoughts?

### PR DESCRIPTION
**Pull request by kaedys**
Added a -stub flag that removes the panic behavior if an unset call is made.  With this flag, unset methods return zero values instead.  For the function signature:
```
Four(string, bool, int) (string, error)
```
The generated code _without_ `-stub` (ie. with the current version of Moq) is:

```
// Four calls FourFunc.
func (mock *MyInterfaceMock) Four(in1 string, in2 bool, in3 int) (string, error) {
	if mock.FourFunc == nil {
		panic("moq: MyInterfaceMock.FourFunc is nil but MyInterface.Four was just called")
	}
	callInfo := struct {
		In1 string
		In2 bool
		In3 int
	}{
		In1: in1,
		In2: in2,
		In3: in3,
	}
	lockMyInterfaceMockFour.Lock()
	mock.calls.Four = append(mock.calls.Four, callInfo)
	lockMyInterfaceMockFour.Unlock()
	return mock.FourFunc(in1, in2, in3)
}
```

With the `-stub` flag in this PR, the generated code is:
```
// Four calls FourFunc.
func (mock *MyInterfaceMock) Four(in1 string, in2 bool, in3 int) (_r0 string, _r1 error) {
	if mock.FourFunc != nil {
		callInfo := struct {
			In1 string
			In2 bool
			In3 int
		}{
			In1: in1,
			In2: in2,
			In3: in3,
		}
		lockMyInterfaceMockFour.Lock()
		mock.calls.Four = append(mock.calls.Four, callInfo)
		lockMyInterfaceMockFour.Unlock()
		_r0, _r1 = mock.FourFunc(in1, in2, in3)
	}
	return
}
```
The `-stub` generate code will return the default zero values for all return types if the function field in the mock struct is unset, rather than panicking.  This is defined as a command line flag (that is off by default) to avoid changing the generator's behavior for existing user.  Fixes #36.

*Note to reviewers:* I made a duplicate of the template variable to avoid cluttering the existing template.  The only lines that I changed in the duplicated template string are line numbers 157-178 in the diff.  All other lines are identical to the existing template string.

### CODE REVIEW

**Comment by kaedys** [comment]
Hmm, tests failing because of changed function signature in `New()`, will correct and update PR.

**Comment by matryer** [comment]
Could we adjust the `_r*` variables to `out1`, `out2`, and `out3` etc?

**Comment by kaedys** [comment]
Sure, that seems reasonable given the names of the input arguments.  Tbh, I don't even remember why I used the `_r#` style.  I'll try to remember to handle it on monday and get a new commit pushed.

**Comment by matryer** [comment]
thanks @kaedys

**Comment by kaedys** [comment]
Updated.  New output:
```Go
// Four calls FourFunc.
func (mock *MyInterfaceMock) Four(in1 string, in2 bool, in3 int) (out1 string, out2 error) {
	if mock.FourFunc != nil {
		callInfo := struct {
			In1 string
			In2 bool
			In3 int
		}{
			In1: in1,
			In2: in2,
			In3: in3,
		}
		lockMyInterfaceMockFour.Lock()
		mock.calls.Four = append(mock.calls.Four, callInfo)
		lockMyInterfaceMockFour.Unlock()
		out1, out2 = mock.FourFunc(in1, in2, in3)
	}
	return
}
```

**Comment by hcliff** [comment]
good shout, perhaps if the non-panicing behavior is desired for “just tracking” we can/should support that with a different  flag without feature creeping this PR

**Comment by matryer** [comment]
Closing due to old age.

**Comment by breml** [comment]
I like this PR.

@kaedys Do you think you could rebase your branch and open a new PR for this?

**Comment by kaedys** [comment]
Sure, I can look at doing that when I have some bandwidth.  Currently under a bit of a crunch, though, so it might be a fewish days.

**Comment by t-Singularity** [comment]
> Sure, I can look at doing that when I have some bandwidth. Currently under a bit of a crunch, though, so it might be a fewish days.

@kaedys  It would be really cool if you could get this PR merged! Thanks!

**Pull request closed without merging**
