### PR TITLE
-stub flag

### PR DESCRIPTION
**Pull request by kaedys**
* Added a -stub flag that removes the panic behavior if an unset call is made.
* With this flag, unset methods return zero values instead.
* Updated tests for altered moq.New() function signature.
* Changed "destination" var and in usage to "source", to reflect its actual functionality (fixes matryer/moq#85).

Per request, rebased #46 against master.  Also integrated a quick fix for #85.

### CODE REVIEW

**Comment by kaedys** [comment]
@breml @t-Singularity Head's up, due to your interest in the prior PR.

**Comment by kaedys** [comment]
Looks like the tests are failing because Go 1.10 and earlier are no longer supported for the version of the packages library being used.

**Comment by t-Singularity** [comment]
@matryer May I ask you to look at the failures for Go 1.10 and earlier?

**Comment by kaedys** [comment]
@matryer reminding you of this PR.

**Comment by sudo-suhas** [comment]
@kaedys would you be willing to rebase this against the master branch? I can undestand if you do not wish to work on this anymore though.

**Comment by kaedys** [comment]
Ya, I'll see if I can find some time to get that done.

**Comment by sudo-suhas** [comment]
Thanks @kaedys for opening this PR. I pulled in the essential changes from this into #132 and moq now supports the `-stub` flag :tada: (see https://github.com/matryer/moq/blob/83ab8dd79f4cd81ed605de6b758d595889103053/pkg/moq/testpackages/channels/queuer_moq.golden.go#L57-L74 for an example of the generated mock)

**Pull request closed without merging**
