### PR TITLE
Added handling/tests for return slice on variadic method

### LINKED ISSUE #99: Variadic args are causing an issue with returning a slice
If you have a variadic method that returns a slice, such as:
```go
MultiSearch(ctx context.Context, searchTerms ...string) []string
```
moq tries to convert the return slice into a variadic parameter:
```go
MutiSearchFunc func(ctx context.Context, searchTerms ...string) ...string
```
which results in a `go/format` error, for example:
```
go/format: 52:79: expected type, found '...' (and 8 more errors)
```

I will submit a pull request shortly with a fix and test for returning slices that catches this issue.

Also, I just want to say thanks for moq!

### PR DESCRIPTION
**Pull request by pehowell**
Let me know if you want me to handle identifying variadic params to `extractArgs()` in a different way, thanks!

This fixes #99

### CODE REVIEW

**Comment by pehowell** [comment]
Hi @matryer, looks like the failures are because newer versions of package dropped support for go versions < 1.11. I can think of a couple of options here:
- moq drops support for 1.10 and below, so I can update the travis file to test 1.11, 1.12, and tip. This would also allow adding go module support in the future.
- moq uses dep or some other means to pin it to a specific version of package

My vote is for the first option, but what does everyone else think?

**Comment by breml** [comment]
I am fine with option 1. This is also in accordance with the Go release policy.

**Comment by pehowell** [comment]
@breml thanks for the feedback. I've removed 1.9 and 1.10 testing environments and added 1.12.

**Comment by sudo-suhas** [comment]
Hey @pehowell thanks for this. The issue is now fixed via #126 so I am closing this PR.

**Pull request closed without merging**
