### PR TITLE
Allow aliasing interface name

### LINKED ISSUE #67: Allow specifying name for generated mock
Right now, the name for the generated mock is `{{.InterfaceName}}Mock` and it works well for most cases. However, I wanted to keep all the generated mocks in a separate `mock` pkg as suggested by Ben Johnson - https://medium.com/@benbjohnson/standard-package-layout-7cdbc8391fc1#f68c. The problem was that I had multiple interfaces with the same name in different packages(`a.APIClient`, `b.APIClient`, `c.APIClient` ...). So what I wanted was to have the mocks of the form `mock.AClient`, `mock.BClient` etc. I forked the repo and made minimal changes to make this possible - [sudo-suhas/moqit](https://github.com/sudo-suhas/moqit). Do you think this is a feature worth having?

### LINKED ISSUE #106: Customizing generated mock name through an optional flag
Especially if one decides to gather all generated mocks in one package like `mocks`, there can be name clashes. (for example consider the case when there are two `Client` interfaces in the code base and both are them are being mocked). For avoiding those name clashes, of course there is a workaround. One can alias the types that are going to be mocked in the `mocks` package and then generate mocks for those aliased types. But that requires exposing those aliased types from `mocks` package which leads to confusion IMO. 

For solving the aforementioned problem I am asking if there can be a flag called `name` indicating name of the mock struct that moq generates.

### PR DESCRIPTION
**Pull request by sudo-suhas**
Implementation based on #57.
~~Additionally, handle the destination pkg having 'mock' in its name.~~ - not necessary, the user can define the alias as per their requirement.

TODO: Update README(need some tips)

Closes #57 
Closes #106 
Closes #67

### CODE REVIEW

**Comment by sudo-suhas** [comment]
For the failures on CI, see #105.

**Comment by matryer** [comment]
retest this please

**Comment by matryer** [comment]
OK the CI should be working again. @sudo-suhas would you be able to resolve the conflicts here (it was non-obvious) and we can get this merged in?

**Comment by sudo-suhas** [comment]
I'll do that right away. Thanks for taking the time

**Comment by sudo-suhas** [comment]
I was able to rebase against master without any conflicts. @matryer Please give some suggestion on how we could document this. Should I add a dedicated section? Something like `Specify alias for mocks`?

**Comment by sudo-suhas** [comment]
Also, if the user is specifying the alias, should we still append `Mock` to it?

**Comment by matryer** [comment]
Just a line in the Usage section of the README will do. What do you think?

**Comment by matryer** [comment]
If the user specifies the name, we should just use the name they choose. They can add `Mock` or not. :)

**Comment by matryer** [comment]
@sudo-suhas would you like to become a maintainer for this project?

**Comment by sudo-suhas** [comment]
> If the user specifies the name, we should just use the name they choose.

I like this too, makes things simpler 😄 . I'll force push a commit with these changes.

> would you like to become a maintainer for this project?

Sure @matryer I'd be _very_ glad to help. I can't say that I understand everything that's going on but I'll try my best.

**Comment by sudo-suhas** [comment]
@matryer Thank you so much for inviting me as a maintainer 🎉!

Could you comment on whether this PR looks good? I'd like to run things by you, at least for some time initially.

**Comment by matryer** [comment]
@sudo-suhas LGTM

**Pull request merged**
