### PR TITLE
rm flag

### PR DESCRIPTION
**Pull request by soniah**

### CODE REVIEW

**Comment by soniah** [comment]
See conversation in https://github.com/matryer/moq/pull/149

**Comment by soniah** [comment]
@sudo-suhas about your question _Is it possible to add a test for this change?_ Short answer - no - not without making significant changes to `main.go`.

`func run()` in `main.go` isn't currently tested. To properly test it you would need to pass in a filesystem interface using something like https://github.com/spf13/afero, which I doubt you want to do.

See various blog articles like these for more explanation:

- http://krsacme.com/golang-fs-tests
- https://stackoverflow.com/questions/16742331/how-to-mock-abstract-filesystem-in-go

So, what would be the next steps? 😄

**Comment by sudo-suhas** [comment]
Thanks @soniah for the PR!

The feature has been tagged and released in [moq `v0.2.3`](https://github.com/matryer/moq/releases/tag/v0.2.3) 🎉

**Comment by mislav** [comment]
@soniah Thank you for this! Just what our project needed. 🚀

**Comment by soniah** [comment]
You're welcome, saves a lot of problems 😊 

In Makefiles you can do something like `MOCKS ?= $(shell find . -type f -name '*_mock_gen.go' -not -path "./vendor/*")` then `rm -f $(MOCKS)` but that's tedious 🤕

**Pull request merged**
