### PR TITLE
Go modules support

### LINKED ISSUE #84: go mod support
Does this tool support Go 1.11 module?

### PR DESCRIPTION
**Pull request by IvanSafonov**
Same as #76. Fixes #84
`go/packages` understands how to locate packages in a module-aware manner.

I've started to use go mod and got a lot of errors like this:
```
<project path outside GOPATH>/vendor/github.com/spf13/viper/viper.go:42:7: could not import github.com/pelletier/go-toml (go/build: importGo github.com/pelletier/go-toml: exit status 1
can't load package: package github.com/pelletier/go-toml: cannot find package "." in:
        <project path outside GOPATH>/vendor/github.com/spf13/viper/vendor/github.com/pelletier/go-toml
```

### CODE REVIEW

**Comment by matryer** [comment]
@IvanSafonov What a great contribution, thanks.

**Comment by omarkohl** [comment]
Any chance of getting this merged?

**Comment by matryer** [comment]
@omarkohl Thanks for the prompt.

**Comment by omarkohl** [comment]
@IvanSafonov there is still a bug #92 . Maybe you could have a look.

**Pull request merged**
