### PR TITLE
Update Golang and tools version for new language idioms

### PR DESCRIPTION
**Pull request by arkadiuszos4chain**
This update addresses compatibility issues with newer Go language idioms. The current version of `moq` fails when encountering certain statements, such as:
```go
for range 5 {
  // ...
}
```
which results in the following error:
```
couldn't load source package: sample.go:110:12: cannot range over 5 (untyped int constant)
```

##Changes:
* Go version: Bumped from 1.18 to 1.22.5
* golang.org/x/tools: Updated from 0.17.0 to 0.24.0
* Replaced usage of deprecated ioutils

### CODE REVIEW

**Comment by ns-skaranth** [comment]
@arkadiuszos4chain could you add a test case that has some of the new constructs in the source somewhere?

**Comment by arkadiuszos4chain** [comment]
> @arkadiuszos4chain could you add a test case that has some of the new constructs in the source somewhere?

@ns-skaranth I'm not sure if I choose best place, but you can check my test case.

**Review by sudo-suhas — APPROVED** [review]
LGTM

**Comment by sudo-suhas** [comment]
@arkadiuszos4chain could you rebase the PR on the master branch? There were some changes made to run tests on the latest stable version

**Comment by arkadiuszos4chain** [comment]
> @arkadiuszos4chain could you rebase the PR on the master branch? There were some changes made to run tests on the latest stable version

@sudo-suhas done.

**Pull request merged**
