### PR TITLE
Fix: add imports for Named Type its Instance Types

### LINKED ISSUE #177: Moq ignores package names of arguments of generic types
When mocking a method with a generic type, moq ignores package names of type arguments.

This works:
```go
package example

//go:generate moq -skip-ensure -stub -rm -out mocks.go . Foo:FooMock

type Bar[T any] struct{}

type Foo interface {
	Foo(bar Bar[Type])
}
```

But this does not:
```go
package example

//go:generate moq -skip-ensure -stub -rm -out mocks.go . Foo:FooMock

import "path/to/pkg"

type Bar[T any] struct{}

type Foo interface {
	Foo(bar Bar[pkg.Type])
}
```

The generated code instantiates `Bar` as `Bar[Type]` instead of `Bar[pkg.Type]`, failing to compile:

```go
// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package example

import (
	"sync"
)

type FooMock struct {
	// FooFunc mocks the Foo method.
	FooFunc func(bar Bar[Type])

	// calls tracks calls to the methods.
	calls struct {
		// Foo holds details about calls to the Foo method.
		Foo []struct {
			// Bar is the bar argument value.
			Bar Bar[Type]
		}
	}
	lockFoo sync.RWMutex
}
```

I've tried workarounds like dot imports and type aliases, but got the same results. If `Bar` type is a built-in like `map`, it works fine.
moq version `v0.2.7`.

### PR DESCRIPTION
**Pull request by TimVosch**
Fixes missing imports and package prefixing to generic types. See #177 

In the following example a method must be mocked which has a return parameter that has a generic type: `otherpackage.Foo`. 

```go
package genericreturn

import "github.com/matryer/moq/pkg/moq/testpackages/genericreturn/otherpackage"

type GenericBar[T any] struct {
	Bar T
}

type IFooBar interface {
	Foobar() GenericBar[otherpackage.Foo]
}
```

```go
package otherpackage

type Foo struct {
	A int
	B string
}
```

Currently mocking `IFooBar` will result in a missing `otherpackage` import and the package prefix to `Foo`. Note: `FoobarFunc: func() GenericBar[Foo]` instead of `FoobarFunc: func() GenericBar[otherpackage.Foo]`.
```
// IFooBarMock is a mock implementation of IFooBar.
//
//	func TestSomethingThatUsesIFooBar(t *testing.T) {
//
//		// make and configure a mocked IFooBar
//		mockedIFooBar := &IFooBarMock{
//			FoobarFunc: func() GenericBar[Foo] {
//				panic("mock out the Foobar method")
//			},
//		}
//
//		// use mockedIFooBar in code that requires IFooBar
//		// and then make assertions.
//
//	}
```

This happens because of an invalid key lookup here, which returns an empty string `""`: [internal/registry/var.go](https://github.com/matryer/moq/blob/373b8f9e00b57d70c32d45f8d765836505a1e527/internal/registry/var.go#L38)

This is fixed by checking if a Named Type has type arguments, and populating imports for those types.
[internal/registry/method_scope.go](https://github.com/matryer/moq/blob/974b193b71073e82986638ac716096806f36b665/internal/registry/method_scope.go#L85-L91)
```go
func (m MethodScope) populateImports(t types.Type, imports map[string]*Package) {
	switch t := t.(type) {
	case *types.Named:
		...
		// The imports of a Type with a TypeList must be added to the imports list
		// For example: Foo[otherpackage.Bar] , must have otherpackage imported
		if targs := t.TypeArgs(); targs != nil {
			for i := 0; i < targs.Len(); i++ {
				m.populateImports(targs.At(i), imports)
			}
		}
```

A new golden test was added for this specific case.

Closes #177
Closes #190

### CODE REVIEW

**Comment by sudo-suhas** [comment]
Expected error message in the `TestParseError` test is `couldn't load source package: ~/moq/pkg/moq/testpackages/_parseerror/service/service.go:3:8: could not import github.com/matryer/notexist (invalid package name: "")`. 

Not sure why the error is `couldn't load source package: err: exit status 1: stderr: go build github.com/matryer/notexist: service.go:3:8: cannot find package "." in: ~/moq/pkg/moq/testpackages/vendor/github.com/matryer/notexist` only on Go 1.19.

**Comment by TimVosch** [comment]
Hmm, this also appears to happen on the main branch. I expect it's an issue unrelated to this PR.
I'll see if I can find something.

```
╭─timvosch@XPS15-ARCH ~/src/moq  ‹373b8f9› 
╰─➤  docker run --rm -it -v `pwd`:/project --workdir /project golang:1.19 go test ./...
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading golang.org/x/tools v0.3.0
go: downloading golang.org/x/mod v0.7.0
go: downloading golang.org/x/sys v0.2.0
?       github.com/matryer/moq  [no test files]
ok      github.com/matryer/moq/example  0.001s [no tests to run]
?       github.com/matryer/moq/generate [no test files]
?       github.com/matryer/moq/internal/registry        [no test files]
ok      github.com/matryer/moq/internal/template        0.001s
--- FAIL: TestGoGenerateVendoredPackages (0.00s)
    moq_test.go:629: Wait: exit status 1 
--- FAIL: TestParseError (0.01s)
    moq_test.go:663: unexpected error: couldn't load source package: err: exit status 1: stderr: go build github.com/matryer/notexist: service.go:3:8: cannot find package "." in:
                /project/pkg/moq/testpackages/vendor/github.com/matryer/notexist
FAIL
FAIL    github.com/matryer/moq/pkg/moq  6.336s
FAIL
```

**Comment by sudo-suhas** [comment]
We can add an additional clause for the error string check to cover errors from both Go 1.18 and Go 1.19.

**Comment by TimVosch** [comment]
I updated the test to also check for `stderr: go build github.com/matryer/notexist`

**Comment by sudo-suhas** [comment]
This change has been released in [`v0.3.2`](https://github.com/matryer/moq/releases/tag/v0.3.2) 🎉

**Pull request merged**
