### PR TITLE
Return OS specific default GOPATH if not set

### PR DESCRIPTION
**Pull request by breml**
See: https://github.com/golang/go/issues/17262

Fixes: #52

### CODE REVIEW

**Comment by breml** [comment]
Rebased, now TravisCI is happy.

**Comment by kaedys** [comment]
Not sure if this is still live, but there's no reason to ad-hoc it.  The standard library package `go/build` has a global `build.Default.GOPATH` that returns the currently set GOPATH, using the environment variable if set, and the default for that operating system if it is not.  You can simply unconditionally return the value of that variable.

**Comment by breml** [comment]
@kaedys Thanks for the hint.

After looking at `go/build`, I found, that maybe even better than using `build.Default.GOPATH` would be to use [`build.Default.SrcDirs()`](https://github.com/golang/go/blob/master/src/go/build/build.go#L243), as this would simplify [`stripGopath`](https://github.com/matryer/moq/blob/master/pkg/moq/moq.go#L329-L334) as well and it does handle some special/edge cases as well (like unquoted `~` which was not expanded to `$HOME` and special cases on different OS).

@matryer if you like this, I can update the PR accordingling.

**Comment by kaedys** [comment]
Note that `SrcDirs()` returns a slice, for which the first item is the GOROOT.  Looking at your updated code, it _should_ work in most cases, but I could see it failing in a couple edge cases, notably if the $GOPATH is nested in the $GOROOT (which _is_ legal, though strongly discouraged).

For example, of `$GOROOT` = `~/go` and `$GOPATH` = `~/go/code`, then the absolute import path for a package might be, for example, `~/go/code/src/github.com/foo/bar`.  Our goal is to get back out `github.com/foo/bar`.  Problem is, it first looks at the `$GOROOT`, as that's the first item in the list, stripping `p` to `/code/src/github.com/foo/bar`.  This no longer matches the `$GOPATH`, and thus `p` is returned as `code/src/github.com/foo/bar`, which isn't a valid canonical import path (unless you happen to have a path that matches `~/go/code/src/code/src/github.com/foo/bar`).

For the purposes of just stripping the GOPATH from the front of the package path, I think you really should just use `build.Default.GOPATH`.  Also not sure what you mean about not expanding the tilde character.  Running my tester program prefixed by `GOPATH=~/testtest`, my `build.Default.GOPATH` is properly set to `/Users/<me>/testtest`.

**Comment by breml** [comment]
About `~` see comment here: https://github.com/golang/go/blob/master/src/go/build/build.go#L220

About `$GOPATH` inside `$GOROOT` you are right, but this is als true for the (rather unusual) case where someone puts a `$GOPATH` inside another `$GOPATH`, which I think would be (technicaly) possible as well. This case is also not covered now.

**Comment by kaedys** [comment]
> About ~ see comment here

That comment is about _quoted_ tilde paths, not unquoted ones.  Unquoted ones are already properly expanded into `build.Default.GOPATH`.  Quoted ones, per that comment, aren't even legal paths, and thus shouldn't be supported anyway.

**Comment by sudo-suhas** [comment]
Hey @breml I want to thank you for having created this PR. I incorporated your changes as part of a larger effort to improve Windows compatibility. I did not want to put you through the hassle of rebasing and updating this PR since it was opened a long time ago. I was invited to maintain the repo recently and will try to be more proactive in the future so that a PR isn't left hanging for so long. I hope you will be just as helpful in the future and look forward to your contributions.  🙂

**Pull request closed without merging**
